index:
    path: /registration
    controller: App\Controller\RegistrationController::registration

privacy_page:
    path: /privacy
    controller: App\Controller\PorivacyController::privacyTemplate

